In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("life_exp.csv")
df

,Unnamed: 0,Life_Expectancy,Average_Temperature,Daily_Screen_Time,Health_Index,Income,Country,Diet_Type,Government_Health_Policy
0,0,72.483571,17.923146,4.357787,71.654576,74294.715447,Country B,Vegetarian,1.0
1,1,69.308678,22.896773,4.560785,68.748497,73109.928448,Country B,Non-Vegetarian,1.0
2,2,73.238443,23.286427,5.083051,73.985736,78248.930090,Country C,Vegetarian,1.0
3,3,77.615149,20.988614,5.053802,78.225520,82709.110470,Country C,Vegan,1.0
4,4,68.829233,24.193571,2.622331,68.808332,72929.102183,Country A,Vegetarian,1.0
...,...,...,...,...,...,...,...,...,...
95,95,62.682425,26.926587,3.307090,62.213250,68760.245347,Country C,Non-Vegetarian,1.0
96,96,71.480601,20.580713,4.899600,69.767467,74406.109077,Country A,Non-Vegetarian,1.0
97,97,71.305276,25.768626,4.307300,72.659149,75924.599005,Country B,Non-Vegetarian,1.0
98,98,70.025567,25.291044,4.812862,69.911027,73274.330776,Country C,Non-Vegetarian,1.0
99,99,68.827064,19.285149,4.629629,70.064881,71061.464871,Country C,Vegan,1.0

In [3]:
df.describe()

,Unnamed: 0,Life_Expectancy,Average_Temperature,Daily_Screen_Time,Health_Index,Income,Government_Health_Policy
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.0
mean,49.500000,69.480767,25.111523,4.064896,69.587608,74368.758472,1.0
std,29.011492,4.540842,4.768345,1.084283,4.475948,4744.899489,0.0
min,0.000000,56.901274,15.406144,0.758733,59.054457,62441.446464,1.0
25%,24.750000,66.995472,20.971697,3.344556,66.820378,70968.995974,1.0
50%,49.500000,69.365219,25.420536,4.097696,69.626849,74399.904642,1.0
75%,74.250000,72.029760,27.690852,4.704437,72.651242,78126.987900,1.0
max,99.000000,79.261391,38.600846,7.852731,79.173729,86449.739694,1.0

###Analiza odnosa Life_Expectancy, Health_Index i Income